### PR TITLE
ENH: Adapt from namedtuple

### PR DESCRIPTION
**Pull request by larsoner**
Maybe?

### CODE REVIEW

**Comment by WarrenWeckesser** [comment]
The line

    from _collections import _tuplegetter

fails in Python 3.7.  The fix from `Lib/collections/__init__.py` in the Python source code is to use:

```
from operator import itemgetter as _itemgetter
try:
    from _collections import _tuplegetter
except ImportError:
    _tuplegetter = lambda index, doc: property(_itemgetter(index), doc=doc)
```
After making that change, I ran the test suite, and `test_pickle` failed:
```
$ python runtests.py -n -t scipy._lib.tests.test_bunch
======================================= test session starts ========================================
platform darwin -- Python 3.7.6, pytest-5.4.2, py-1.8.1, pluggy-0.13.1
rootdir: /Users/warren/repos/git/forks/scipy, inifile: pytest.ini
plugins: forked-1.1.3, xdist-1.32.0
collected 24 items                                                                                 

../.. .....F..................                                                               [100%]

============================================= FAILURES =============================================
__________________________________ TestMakeTupleBunch.test_pickle __________________________________
/Users/warren/mc37scipy/lib/python3.7/site-packages/scipy-1.6.0.dev0+393fd47-py3.7-macosx-10.9-x86_64.egg/scipy/_lib/tests/test_bunch.py:47: in test_pickle
    s = pickle.dumps(self.result)
E   _pickle.PicklingError: Can't pickle <function Result.__new__ at 0x117a87440>: import of module 'namedtuple_Result' failed
        self       = <scipy._lib.tests.test_bunch.TestMakeTupleBunch object at 0x117abb650>
===================================== short test summary info ======================================
FAILED ../../::TestMakeTupleBunch::test_pickle - _pickle.PicklingError: Can't pickle <function Re...
=================================== 1 failed, 23 passed in 0.20s ===================================
```

**Comment by larsoner** [comment]
> After making that change, I ran the test suite, and test_pickle failed:

Weird, one thing preserved in this PR is the logic for the `result.__module__`, which should be what determines this. I'm not sure what could be the cause of this, it doesn't make any sense (and I can't replicate locally on Python 3.8). You could try tweaking the `result` bits to see if you can get it to work.

In the meantime I'll try to get a suitable 3.7 env working

**Comment by larsoner** [comment]
Replicated on 3.7, let me see if I can fix it...

**Comment by larsoner** [comment]
Pushed a fix, probably because I used `exec` instead of `eval` in creating `__new__` (?) I needed to set `__new__.__module__`. Now it seems to work for me on 3.7 and 3.8

**Comment by WarrenWeckesser** [comment]
There is still a fundamental problem:  the values of the extra fields are stored in a dictionary attached to the *class*, which means all instances of the new class share the same values for the extra fields.

Example: define a `Foo` class, and create an instance `f1`:
```
In [11]: from scipy._lib._bunch import make_tuple_bunch                     

In [12]: Foo = make_tuple_bunch('Foo', ['a', 'b'], ['w', 'beta'])

In [13]: f1 = Foo(a=1, b=2, w=-1, beta=0)

In [14]: f1
Out[14]: Foo(a=1, b=2, w=-1, beta=0)
```
Create a second instance `f2`:
```
In [15]: f2 = Foo(a=3, b=4, w=999, beta=1.0)

In [16]: f2
Out[16]: Foo(a=3, b=4, w=999, beta=1.0)
```
`f1` now has the same values for `w` and `beta` as `f2`:
```
In [17]: f1
Out[17]: Foo(a=1, b=2, w=999, beta=1.0)
```

**Comment by larsoner** [comment]
Makes sense, can you push a test that captures this to your branch? Then I'll see if this other method can be fixed such that it still passes

**Comment by WarrenWeckesser** [comment]
I pushed a new unit test to my PR.  CI is running now.

**Comment by larsoner** [comment]
Fixed by removing `__slots__` and allowing `__dict__` but trying to prevent users from setting values. All tests pass locally at least

**Comment by WarrenWeckesser** [comment]
Did you commit and push all the changes that you made to get the tests to pass?  With your latest version, any attempt to create an instance fails, because the attribute `_extra_field_names` that is used in `__init__` has never been set.

You called the attribute `_extra_fields` in `class_namespace`.   If I change `__init__` to use that name instead, it works 🎉.  I'll experiment some more with these changes this afternoon, and if all is well, merge it into my PR.

**Comment by larsoner** [comment]
Whoops, sorry about that. I was playing around with naming a bit and accidentally pushed a broken one before

**Comment by WarrenWeckesser** [comment]
@larsoner, I merged your changes into my PR.  Thanks for working this out!

I'm now going to make some unilateral, opinionated changes to your changes 😄.

**Pull request merged**
